# Generated by Django 5.2.7 on 2025-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
