# Generated by Django 5.1.5 on 2025-10-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_dropitem_price_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
